## **1 Layer Neural Network**

In [6]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
A = 2*np.random.random((3,4)) - 1
S = 2*np.random.random((4,1)) - 1
for j in range(60000):
  l1 = 1/(1+np.exp(-(np.dot(X,A))))
  l2 = 1/(1+np.exp(-(np.dot(l1,S))))
  l2_delta = (y - l2)*(l2*(1-l2))
  l1_delta = l2_delta.dot(S.T) * (l1 * (1-l1))
  A += X.T.dot(l1_delta)
  S += l1.T.dot(l2_delta)

In [7]:
print(A)

[[ 7.38364633  5.06844165  1.52243904  0.03756423]
 [ 7.39688227  5.05364456  1.49704297  0.16008939]
 [-3.42415651 -7.79181989 -2.4801834   2.57480678]]


In [8]:
print(S)

[[ 12.92195488]
 [-11.40823925]
 [ -4.10473785]
 [ -5.75217445]]


## **2 Layer Neural Network**

In [10]:
#sigmoid func
def nonlin(x,deriv=False):
  if(deriv==True):
    return x*(1-x)
  return 1/(1+np.exp(-x))

In [13]:
#i/p dataset
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T

#o/p dataset
y = np.array([[0,0,1,1]]).T

In [14]:
# seed random numbers to make calculation
# deterministic
np.random.seed(1)

In [16]:
# initialize weights randomly with mean 0
A = 2*np.random.random((3,1)) - 1

In [20]:
for iter in range(10000):
  # forward propagation
  l0 = X
  l1 = nonlin(np.dot(l0,A))

  # how much did we miss?
  l1_error = y - l1

  # multiply how much we missed by the
  # slope of the sigmoid at the values in l1
  l1_delta = l1_error * nonlin(l1,True)

  #UPDATE WEIGHTS
  A = np.dot(l0.T,l1_delta)

In [22]:
print ("Output Ye Hai:")
print (l1)

Output Ye Hai:
[[0.4942777 ]
 [0.49159967]
 [0.54999193]
 [0.54733874]]
